# Generated by Django 2.0.6 on 2018-10-14 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 6, 55, 59, 730216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_link',
            field=models.CharField(default=None, max_length=2083, null=True),
        ),
    ]
