# Generated by Django 2.0.6 on 2018-10-14 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181014_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 6, 58, 6, 381525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_link',
            field=models.CharField(blank=True, default=None, max_length=2083),
        ),
    ]
