# Generated by Django 2.0.6 on 2018-10-14 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20181014_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 7, 37, 7, 837332, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 7, 37, 7, 837332, tzinfo=utc)),
        ),
    ]
