# Generated by Django 2.0.6 on 2018-10-14 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20181014_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 10, 14, 47, 517380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 10, 14, 47, 517380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
