# Generated by Django 2.0.6 on 2018-10-14 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20181014_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 17, 56, 8, 628854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 17, 56, 8, 628854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_link',
            field=models.CharField(blank=True, default=None, max_length=2072),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
