# Generated by Django 2.0.6 on 2018-10-31 05:39

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20181027_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 5, 39, 17, 630161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 5, 39, 17, 630161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
