# Generated by Django 2.0.6 on 2018-10-15 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20181015_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 11, 58, 35, 93210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 58, 35, 93210, tzinfo=utc)),
        ),
    ]
