#!/bin/sh
source ./django/bin/activate
# /cloudsql/cloud_sql_proxy -instances="[django-database]"=tcp:3306
# python manage.py makemigrations
# python manage.py migrate
nohup python3 -u ./manage.py runserver 0.0.0.0:8080 > log.txt &
