# Generated by Django 2.0.6 on 2018-11-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('owner', 'OWNER'), ('editor', 'EDITOR'), ('member', 'MEMBER')], max_length=30),
        ),
    ]
