# Generated by Django 2.0.6 on 2018-10-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('location', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=2550.0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='entity.Entity')),
            ],
        ),
    ]
