# Generated by Django 2.0.6 on 2018-11-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181111_1907'),
        ('event', '0002_auto_20181111_2140'),
    ]

    operations = [
    ]
