# Generated by Django 2.0.6 on 2018-08-30 13:21

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('company_avatar', models.ImageField(default=None, null=True, upload_to=company.models._upload_company_avatar)),
                ('company_size', models.DecimalField(decimal_places=0, max_digits=5)),
                ('industry', models.CharField(max_length=30)),
                ('specialist_area', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=20)),
                ('type_of_business', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=80)),
                ('summer_students', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('administrator', 'Administrator'), ('owner', 'Owner')], max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
