# Generated by Django 2.0.6 on 2018-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_size',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='companymembers',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('editor', 'Editor'), ('owner', 'Owner')], max_length=30),
        ),
    ]
