# Generated by Django 2.0.6 on 2018-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='type_of_business',
            field=models.CharField(choices=[('merchandising', 'Merchandising'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('hybrid', 'Hybrid')], default='services', max_length=25),
        ),
    ]
