# Generated by Django 2.0.6 on 2018-09-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180908_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='companyapplication',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyApplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
