# Generated by Django 2.0.6 on 2018-09-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20180908_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='application',
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
