# Generated by Django 2.0.6 on 2018-09-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180908_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='company.Company'),
        ),
    ]
