# Generated by Django 2.0.6 on 2018-09-22 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0009_auto_20180922_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyMembers',
            new_name='Member',
        ),
    ]
