# Generated by Django 2.0.6 on 2018-09-24 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20180922_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='date_submitted',
            field=models.DateField(default=datetime.date(2018, 9, 25)),
        ),
    ]
