# Generated by Django 2.0.6 on 2018-10-15 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import entity.models.entity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateField(default=None, null=True)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.TextField(default=None, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Your name can only include characters 0-9, A-Z or a-z.', regex='^[\\w|\\W]*$')])),
                ('avatar', models.ImageField(default=None, null=True, upload_to=entity.models.entity._upload_company_avatar)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'MEMBER'), ('editor', 'EDITOR'), ('owner', 'OWNER')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.Entity')),
                ('size', models.DecimalField(decimal_places=0, max_digits=5)),
                ('industry', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=30)),
                ('specialist_area', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=20)),
                ('website', models.URLField(max_length=20)),
                ('type_of_business', models.CharField(choices=[('merchandising', 'Merchandising'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('hybrid', 'Hybrid')], default='services', max_length=25)),
                ('address', models.CharField(max_length=80)),
                ('summer_students', models.BooleanField(default=False)),
            ],
            bases=('entity.entity',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entity.Entity')),
                ('description', models.TextField(max_length=2550.0)),
                ('website', models.CharField(max_length=2056)),
            ],
            bases=('entity.entity',),
        ),
        migrations.AddField(
            model_name='member',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='entity.Entity'),
        ),
    ]
