# Generated by Django 2.0.6 on 2018-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=2550.0),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.CharField(max_length=2056),
        ),
    ]
