# Generated by Django 2.0.6 on 2018-10-10 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
