# Generated by Django 2.0.6 on 2018-10-24 08:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20181024_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=tinymce.models.HTMLField(max_length=2550.0),
        ),
    ]
