# Generated by Django 2.0.6 on 2018-10-24 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20181024_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specialist_area',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
