# Generated by Django 2.0.6 on 2018-08-23 06:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default/avatar.png', upload_to=user.models.upload_profile_image),
        ),
    ]
