# Generated by Django 2.0.6 on 2018-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
