# Generated by Django 2.0.6 on 2018-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='introduction',
            field=models.TextField(default='Nothing', max_length=300),
            preserve_default=False,
        ),
    ]
