# Generated by Django 2.0.6 on 2018-08-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_consultant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='area_of_expertise',
        ),
        migrations.AddField(
            model_name='consultant',
            name='certifications',
            field=models.TextField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='consultant',
            name='current_occupation',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
