# Generated by Django 2.0.6 on 2018-10-24 07:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181024_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=user.models._upload_profile_image),
        ),
    ]
