# Generated by Django 2.0.6 on 2018-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_consultant_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='area_of_expertise',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='contact_email',
            field=models.EmailField(default=None, max_length=30, null=True),
        ),
    ]
