# Generated by Django 2.0.6 on 2018-08-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180827_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='certifications',
            field=models.TextField(max_length=120),
        ),
    ]
