# Generated by Django 2.0.6 on 2018-08-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180827_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='certifications',
        ),
    ]
