# Generated by Django 2.0.6 on 2018-08-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_consultant_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='certifications',
        ),
    ]
