# Generated by Django 2.0.6 on 2018-08-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_consultant_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='certifications',
            field=models.TextField(default=None, max_length=120, null=True),
        ),
    ]
