# Generated by Django 2.0.6 on 2018-08-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_consultant_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='certifications',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
