# Generated by Django 2.0.6 on 2018-08-27 09:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_consultant_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=user.models._upload_profile_image),
        ),
    ]
